### ISSUE TITLE
instead of assertEquals(a, b)  use azzert.that(a, is(b)), same for assertNotEquals

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team3#105]
e.g., in pruneTests,UnboxTests

**Comment by anny234** [comment]
I found use of assertEquals with delta (for doubles).
Is there a good way to convert it to azzert.that or should I leave it as is?
![image](https://user-images.githubusercontent.com/33667684/48796473-63854600-ed08-11e8-8a67-c5668dff8ff5.png)
![image](https://user-images.githubusercontent.com/33667684/48796490-6b44ea80-ed08-11e8-9eea-47dad33772b0.png)

**Comment by anny234** [comment]
The only uses of assertEquals left are in class azzert and it's tests (testing azzert.assertEquals) and RealStatisticsTest with the delta as I mentioned above.
screen dump as proof:
![image](https://user-images.githubusercontent.com/33667684/48796685-ec9c7d00-ed08-11e8-89c6-734f061e635f.png)

**Comment by anny234** [comment]
I can't find a way to change assertEquals for doubles (because it needs a third argument -> delta) so I'm closing this
