### ISSUE TITLE
Elad Undler - personal work

### ISSUE THREAD

**Issue by anny234** [TechnionYP5779/team3#111]

**Comment by yossigil** [comment]
please specify which TDD you did, which class you documented, and which were the 3-5 most heavy issues you did

**Comment by eladyundler** [comment]
TDDs I worked on: Rectangle #63  and RealList  #64 
Some of difficult issues I worked on:

Most my work was on issue #35 (**increasing code coverage**)
Unit tests for class idiomatic #17 
consolidate class Wrapper into Outer #33
eliminate all assertTrue #88

**Comment by yossigil** [comment]
#108 : similar comments.

**Comment by eladyundler** [comment]
Main things I worked on Sprint One : 
Integrate **Google Maps API** into our website - searching spots on a map and trasforming an address into quardinates(issues like #199 )
**Design** several pages (issues like #151 #156 #157 ) 
Create **Servlets** to support search and orders( issues like #202 )
Fixed bugs and modifying features (issues like #184)
