### ISSUE TITLE
Polish your code: Utils.cantBeNull(x) -> cantBeNull(x)

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team3#117]

**Comment by IluhaBratan** [comment]
While trying to achieve this - I found out the method cantBeNull doesn't exist. Should I create a new or is there one I did not find?
Image provided:
![image](https://user-images.githubusercontent.com/23378405/48737128-e1d4e000-ec55-11e8-8527-95469ab37d64.png)

**Comment by yossigil** [comment]
go find the method in history. it was there!
