### ISSUE TITLE
find who added @SuppressWarnings("all"), and why they did it

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team3#127]
eliminate this, and reflect

**Comment by anny234** [comment]
![image](https://user-images.githubusercontent.com/33667684/48821358-99a2e400-ed61-11e8-9683-9091c0e70a77.png)
They are there because there is no other way to remove the warning the function name is same as class. Answered in #49

**Comment by yossigil** [comment]
there are still null warnings that you mask with this
