### ISSUE TITLE
Make a survey, collect results.

### ISSUE THREAD

**Issue by DanielaDii** [TechnionYP5779/team3#129]
- [x] Write a survey for teachers and students

- [ ] Send it to at least 5 schools.

- [ ] Analyse data.

- [ ] Make conclusions about which features are the most important for teachers and students.

**Comment by DanielaDii** [comment]
Abort. Reason: team now works on parking project

**Comment by yossigil** [comment]
If you did any work on this, it should be documented though

**Comment by DanielaDii** [comment]
@yossigil  I only wrote a survey and sended it to my teachers from high school, also asked friends to send it to their high schools. I got only a few answers from people before you said to abort it(survey was online less than three days). Would else would you like to know?

**Comment by DanielaDii** [comment]
https://docs.google.com/forms/d/1vLqgW-Mn9SVv3_Qg2BcX7Sax22rzP8IJIh5Km10z_nU/edit
https://docs.google.com/forms/d/1NAFF1xbuFCdaoXEmePDAwyZyvrF_ZQrNk7ldIfaXBJU/edit

Surveys. One for teachers one for students(to easily see differences in their preferences).

**Comment by anny234** [comment]
Closing because it is no longer relevant for current project.
