### ISSUE TITLE
Choose DB for the project

### ISSUE THREAD

**Issue by anny234** [TechnionYP5779/team3#132]

**Comment by eric-K1** [comment]
The DB I recommend for the current sprint is SQLite.

First I considered whether we need a NoSQL DB (like MongoDB for example). After reading up on the possible use cases and benefits of not using the SQL model, I decided against it. Our data will mainly be transactional and should exhibit [ACID](https://en.wikipedia.org/wiki/ACID_(computer_science)) properties. In addition, if we choose for example MongoDB, the team would have to learn a whole new paradigm, as well as its weaknesses and best practices. For these reasons I decided to go for a regular SQL database.

There are quite a few alternatives to choose from when it comes to SQL based databases, such as MySQL which is the most well known, MariaDB which is an actively maintained fork of it, and Postgres which is a popular alternative. There is also SQLite, which does not require a server, and is self contained within a single file. This is the main property and reason I recommend this DB. This will help us prototype more easily, and is a good choice for Sprint One. SQLite is also [ACID compliant](https://www.sqlite.org/transactional.html) which ensures correctness.

We should direct all DB accesses through a singular DB manager API, which will allow us to replace our DB of choice later on. After our first MVP, we will know our needs better, and will be able to make a more informed decision for the rest of the project.

**Comment by brosenan** [comment]
The phrase "Doesn't need a server" is quite misleading. Every computer software needs a computer to run on, and a shared database in a web application (shared among different users) needs to reside on the server. SQLite has the advantage that it does not incur its own _process_, that is, it runs as a library over whichever software uses it, but this has both an advantage and a disadvantage.

The advantage is that you have one thing less to worry about. The disadvantage is that you bound your architecture to a single node. Are you familiar with the "three-tier architecture"? This architecture divides between a stateless server running the logic of your app, and a stateful database software / cluster. This separation allows for running any number of instances of the stateless servers. This allows you to support throughput and availability. The key to that is that the database is a separate process, connected to the server via the network (they can initially run on the same computer, but as the system scales out, they can be split into separate computers and even separate clusters). MySQL/MariaDB (same software, different community) and PostgreSQL will all give you that capability. SQLite won't.

**Comment by eric-K1** [comment]
Sorry for using an inaccurate term, though I did base it on the [official website](https://sqlite.org/serverless.html).

My argument for using SQLite was that we do not need such scalability for our first MVP, and that we can design the system in such a way that we can replace it later on after we receive feedback on our result.

**Comment by brosenan** [comment]
I agree with your logic, but please bare in mind that this will have to change for your final product.
