### ISSUE TITLE
Plan DB schema

### ISSUE THREAD

**Issue by anny234** [TechnionYP5779/team3#135]

**Comment by yanivbaldi** [comment]
![image](https://user-images.githubusercontent.com/37808851/49219624-7ff64200-f3dc-11e8-9e3e-9844cf56afd6.png)

**Comment by anny234** [comment]
@yanivbaldi I think address should be in parking table instead of user table.

**Comment by yanivbaldi** [comment]
@anny234 Every user has address, i assumed that the parking is associated to user. i think that we should have the user's address even if that user did not sale his parking yet.

**Comment by anny234** [comment]
@yanivbaldi I think parking spot owners usually own more than one spot in one address

**Comment by yanivbaldi** [comment]
but we discussed about private parking, No? @yossigil
