### ISSUE TITLE
Choose web framework to use

### ISSUE THREAD

**Issue by anny234** [TechnionYP5779/team3#136]

**Comment by anny234** [comment]
A simple tutorial for web HTTP server:
[here](https://medium.com/@ssaurel/create-a-simple-http-web-server-in-java-3fc12b29d5fd)
A better way to do things (but more complex) is probably using Servlet. Tutorial:
[here](https://www.journaldev.com/2114/servlet-jsp-tutorial)

**Comment by yossigil** [comment]
check out what other teams did

**Comment by anny234** [comment]
Most java frameworks for web servers seem to be based on servlets. Since we are inexperienced in web development I propose we use Servlets for start to familiarize with it.
