### ISSUE TITLE
Fix contributors file

### ISSUE THREAD

**Issue by yanivbaldi** [TechnionYP5779/team3#142]

**Comment by yanivbaldi** [comment]
![image](https://user-images.githubusercontent.com/37808851/49231276-46343400-f3fa-11e8-9acd-b92d1e7107cf.png)

**Comment by yossigil** [comment]
commit #?
Pull request?

**Comment by yossigil** [comment]
LINK

**Comment by yossigil** [comment]
#97 - please be more independent in the future.

**Comment by yanivbaldi** [comment]
65a9403
