### ISSUE TITLE
Create CSS File for Primary/Secondary colors

### ISSUE THREAD

**Issue by IliaSmagloy** [TechnionYP5779/team3#160]
Should be according to the [virtual meeting number 2](https://github.com/TechnionYP5779/team3/wiki/Virtual-Meeting-Number-2:-Escalation-of-work-on-the-parking-Project).

**Comment by DanielaDii** [comment]
![default](https://user-images.githubusercontent.com/44427246/49300700-8b746680-f4cb-11e8-8df9-01c1149b7d5b.png)

**Comment by DanielaDii** [comment]
This demonstrates colors.

**Comment by DanielaDii** [comment]
`body {
	margin: 0px;
    border: 20px solid SkyBlue;
    padding: 25px;
    background-image: linear-gradient(white , white, white, Ivory );
    /*background-color: white; you can remove gradient line and
    use this insted*/
}

h1 {
    
    color: RoyalBlue;
   
    letter-spacing: 3px; /*makes space between letters bigger,
    fell free to remove this if you dont like it*/
    text-shadow: 3px 3px LightGray; /*obviously creates shadow,
    fell free to remove this if you dont like it*/
}

h2 {
    
    color: SeaGreen;
}

p {
    /*text-indent: 15px;    put this on if you want to have tab
    in the beginning of the paragrath*/
    color: MidnightBlue;
}


.button { 
    /* write: <button class="button">Button_text</button>
    to make a styled button*/
    background-color: RoyalBlue;
    border: none;
    color: white;
    text-align: center;
    font-size: 16px;
    cursor: pointer;
    padding: 10px 20px;
    transition-duration: 0.4s;
}

.button:hover {
    background-color: DodgerBlue;
}

.button2 {background-color: SeaGreen;} /*<button class="button button2">*/

.button2:hover {
    background-color: #17c578;
}
`

**Comment by DanielaDii** [comment]
If somebody it team is interested to learn more about CSS, there are many nice tutorials here;
https://www.w3schools.com/css/css_colors.asp

**Comment by DanielaDii** [comment]
tutorial on how to link to CSS. @IliaSmagloy @eladyundler @yanivbaldi  maybe you will need this
https://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.birt.doc%2Fbirt%2Ffm-HowToLinkACSSFile.html

**Comment by DanielaDii** [comment]
For now until team will decide where they need css to be placed, I'll post it as text here.

body {
	margin: 0px;
    border: 20px solid SkyBlue;
    padding: 25px;
    background-image: linear-gradient(white , white, white, Ivory );
    /*background-color: white; you can remove gradient line and
    use this insted*/
}

h1 {
    
    color: RoyalBlue;
   
    letter-spacing: 3px; /*makes space between letters bigger,
    fell free to remove this if you dont like it*/
    text-shadow: 3px 3px LightGray; /*obviously creates shadow,
    fell free to remove this if you dont like it*/
}

h2 {
    
    color: SeaGreen;
}

p {
    /*text-indent: 15px;    put this on if you want to have tab
    in the beginning of the paragrath*/
    color: MidnightBlue;
}

/*----------------button styles-------------------*/
.button { 
    /* write: <button class="button">Button_text</button>
    to make a styled button*/
    background-color: RoyalBlue;
    border: none;
    color: white;
    text-align: center;
    font-size: 16px;
    cursor: pointer;
    padding: 10px 20px;
    transition-duration: 0.4s;
}

.button:hover {
    background-color: DodgerBlue;
}

.button2 {background-color: SeaGreen;} /*<button class="button button2">*/

.button2:hover {
    background-color: #17c578;
}
/*-------------------------------------------------------------*/

/*---------------------navigation bar style--------------------*/
/*usage example:
<ul>
  <li><a class="active" href="#home">Home</a></li>
  <li><a href="#news">News</a></li>
</ul>
*/
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #17c578;
}

li {
    float: left;
}

li a {
    display: block;
    background-color: #17c578;
    border: none;
    color: white;
    text-align: center;
    font-size: 16px;
    font-family: sans-serif;
    cursor: pointer;
    padding: 10px 20px;
    transition-duration: 0.4s;
    text-decoration: none;
}

li a:hover {
    background-color: SeaGreen;
    color: white;
}
.active {
    background-color: SeaGreen;
}
/*-------------------------------------------------------------*/
