### ISSUE TITLE
Prepare a team wiki with a schedule for the semester, including all constraints.

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team3#2]

**Comment by anny234** [comment]
Done [Project Schedule](https://github.com/TechnionYP5779/team3/wiki/Project-Schedule)

**Comment by anny234** [comment]
[](url)

**Comment by yossigil** [comment]
seems as if Anny is working the most this week. please update

**Comment by anny234** [comment]
Changed the vacation week
