### ISSUE TITLE
Not all team members are set properly on github

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team3#42]

**Comment by yossigil** [comment]
i would like the assigned members to close the issue, saying what they did...

**Comment by yossigil** [comment]
what's up?

**Comment by IluhaBratan** [comment]
I've added a profile picture :)

**Comment by yossigil** [comment]
@IluhaBratan : please use a name that is not so different from your real name.

**Comment by IliaSmagloy** [comment]
Changed the name as asked, closing the issue :)
