### ISSUE TITLE
Define class range using tdd

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team3#61]
class range represents a range of integers, which could be infinite.

- [x] erase everhing in the class, and commit your erases.
use tdd to develop the class, as follows:
do at least one comit for each checkbox.

- [x] rang.from(2) create the infinite range 2.... 
- [x] range.from(2).from() returns the  starting point of the range
 - [x] range.from(2).to(6) returns the range 2,3,4,5
 - [x] range.to(2) returns the infinite range ..., -3, -2,-1,0,1
- [x] range.to(2).from() should return a null pointer
- [x] range.to(2).from(-5) is the range -5, -4, ...,0,1
- [x] range.numbers return an iterator over all integers in the range. 
- [x] range.to(10).interset(range.from(3)) crate the intersection range
- [x] range.from(x).to(y).includes(z) specifiy by yourself.

**Comment by yossigil** [comment]
use labels as necessary

**Comment by DanielaDii** [comment]
@dormaayan What should range.from(2).from() return? Iterator?

**Comment by DanielaDii** [comment]
@dormaayan can you explain what did you mean us to do with boxes 4 and 5? Cause you can't have static and not-static method, with the same name. And it's not subclass, because you wrote that both return "range" type...

**Comment by anny234** [comment]
2b675b4

**Comment by yanivbaldi** [comment]
![image](https://user-images.githubusercontent.com/37808851/48983161-2f3ccb80-f0f4-11e8-839d-3e6f226e463a.png)

Fixed. 100% coverage.
