### ISSUE TITLE
use tdd to develop a fluent api that represents an arithemtical progression over BigInteger

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team3#62]
See #61  on how to define the fluent API.
Add checkboxes as necessary, note that default first value is zero, default step should e zero, and default count is infinity

**Comment by yossigil** [comment]
use issues labels as necessary

**Comment by eric-K1** [comment]
@dormaayan @yossigil 
What do you mean by count? Do you want the sequence to have an end?
Also how should I represent infinity? There is no such concept in BigInteger.

**Comment by yossigil** [comment]
`        (current.compareTo(end) >= 0) ? false : true;`

You must be kidding...

**Comment by eric-K1** [comment]
fixed
