### ISSUE TITLE
Use tdd to develop representing recangles in the plane defined by two corner points

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team3#63]
see #61 , see #62

**Comment by anny234** [comment]
@dormaayan Can you elaborate about what functions this class has?
Thanks :-)

**Comment by dormaayan** [comment]
@anny234 Part of the issue is to define the exact functionality by yourself.
Feel free to be creative :)

**Comment by yanivbaldi** [comment]
![image](https://user-images.githubusercontent.com/37808851/48982621-b0449480-f0ed-11e8-9328-9f688588070e.png)

Checked. 100% coverage.
