### ISSUE TITLE
use tdd to define a class that defines a list of pairs of real numbers

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team3#64]
this list could be used e.g., for representing a set of data points to draw in an xy graph, 
e.g., x is time and y is weight. the series is the list of data points.

- [x]  function recod(x,y)
- [x] iteration over pairs sorted by
- [x] statistics, such as count of data points.
- [x] implement linear regression https://en.wikipedia.org/wiki/Simple_linear_regression

**Comment by anny234** [comment]
please add reference to the commit

**Comment by anny234** [comment]
b43b41ebefe84355601fd176cb8ce16df040048f

**Comment by yossigil** [comment]
please use a proper comment on the commit:

https://help.github.com/articles/closing-issues-using-keywords/

**Comment by anny234** [comment]
@yossigil Since we can't change the commit (like you said). Can we close the issue?
