### ISSUE TITLE
Make sure all closed issues have an assignee

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team3#70]
_From @yossigil on November 8, 2018 10:48_

each one of you will need to make a report on what he did for the sprint, this report should include all non duplicate issues that he closed.

For this reason, we need to make sure that all duplicates are marked duplicate.

_Copied from original issue: TechnionYP5779/team6#61_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team1#57

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team2#53

**Comment by yossigil** [comment]
well, i checked the issues. this is not the case yet

**Comment by anny234** [comment]
What closed issues are unassigned? I left only the duplicates

**Comment by anny234** [comment]
Never mind, I found it. Sorry

**Comment by yossigil** [comment]
please attach a screen dump. i am not convinced that it is closed.

**Comment by anny234** [comment]
![image](https://user-images.githubusercontent.com/33667684/48229749-aca4d400-e3b1-11e8-8fa6-a9e19858336c.png)
![image](https://user-images.githubusercontent.com/33667684/48229765-b4fd0f00-e3b1-11e8-92a9-f71b47c840f1.png)
![image](https://user-images.githubusercontent.com/33667684/48229779-bb8b8680-e3b1-11e8-9a4a-36ba87976b5f.png)
![image](https://user-images.githubusercontent.com/33667684/48229790-c3e3c180-e3b1-11e8-955b-22c21ec0f3af.png)
![image](https://user-images.githubusercontent.com/33667684/48229807-cba36600-e3b1-11e8-85bd-65d2f52e23f9.png)

Everything but duplicates has assignee
