### ISSUE TITLE
use TDD to define class angle

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team3#71]
_From @yossigil on November 8, 2018 11:1_

that represents an angle on the plane; angles can be added, negated and substracted
here are some hints.

- [x] angle.degrees(20) creates an angle of 20 degrees
- [x] angle.radians(1) creates an angle of 1 radian
- [x] angle.pi is an angle of pi radians
- [x] angle.halfPi is an engle of half Pi radians
- [x] angle.halfPi.add(angle.degrees(20)) is an engle of half Pi radians + 20 radians
- [x] angle.halfPi.add((20)) is an engle of half Pi radians + 20 degrees
- [x] angle.pi.degrees() is 180
- [x] angle.of(20).degrees() is 180
- [x] angle.pi.radians() is PI/2

be sure to create code that try to cheat the tests, e.g. 
`class angle { static angle degrees(double x) { return new angle(20); }`

_Copied from original issue: TechnionYP5779/team6#62_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#96

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team4#91

**Comment by eladyundler** [comment]
![145a0e4c-2b25-4d76-9175-f3bb52831946](https://user-images.githubusercontent.com/38835610/48983007-4975aa00-f0f2-11e8-81f3-faada5bec082.png)

**Comment by eladyundler** [comment]
Checked. 100% coverage
