### ISSUE TITLE
make sure all issues, including closed ones, have a milestone

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team3#72]
_From @yossigil on November 8, 2018 16:36_

to do so, apply searches in the issues tab of github

_Copied from original issue: TechnionYP5779/team1#60_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team2#55

**Comment by yossigil** [comment]
again, not done. please do not close without a screen dump

**Comment by anny234** [comment]
![image](https://user-images.githubusercontent.com/33667684/48229936-1d4bf080-e3b2-11e8-851e-6c98e1e4e35f.png)
![image](https://user-images.githubusercontent.com/33667684/48229945-2472fe80-e3b2-11e8-8b33-3d837f818537.png)
![image](https://user-images.githubusercontent.com/33667684/48229955-2b017600-e3b2-11e8-9277-901cda4e6c03.png)
![image](https://user-images.githubusercontent.com/33667684/48229963-33f24780-e3b2-11e8-8cd2-e315eba836c1.png)
![image](https://user-images.githubusercontent.com/33667684/48229982-3b195580-e3b2-11e8-8773-69ec35e3f95e.png)
![image](https://user-images.githubusercontent.com/33667684/48230024-55533380-e3b2-11e8-9685-b17259d75e0b.png)
![image](https://user-images.githubusercontent.com/33667684/48230032-5be1ab00-e3b2-11e8-9f94-4dba62899a51.png)

Everything has a milestone

**Comment by yossigil** [comment]
not done

**Comment by anny234** [comment]
Fixed the new issues.
But I think it's very confusing to reopen old issue after they were completed at the time but because of new development (new issues being made in this example) they become "not done". 
I think it is better to open a new issue for it, so we see it at the top of the issue list.

**Comment by yossigil** [comment]
you are right in general. the problem here was lack of team work. someone closed the issue, others did not notice it.

**Comment by anny234** [comment]
What do you mean? I closed it. Everything has milestone always (but the new issues you are adding until anyone notices)
