### ISSUE TITLE
Check again that you do not use junit Assert, but only class azzert

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team3#79]
_From @yossigil on November 14, 2018 9:14_

You can do this manually, or write a script. it is up to you. 

_Copied from original issue: TechnionYP5779/team6#79_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#76

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#61

**Comment by anny234** [comment]
![image](https://user-images.githubusercontent.com/33667684/48543445-3c72e280-e8ca-11e8-86be-6534140e8e06.png)
Only in class azzert (because it inherits from Assert)

**Comment by yossigil** [comment]
lgtm

**Comment by anny234** [comment]
@yossigil Where is it? because when I search I get the result as I posted in my previous comment.

**Comment by yossigil** [comment]
nice!
