### ISSUE TITLE
Document a push procedure in a wiki page

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team3#80]
_From @yossigil on November 14, 2018 9:11_

Should include formatting, cleanup, tests, spartanization etc.

_Copied from original issue: TechnionYP5779/team6#78_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#122

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#107

**Comment by IliaSmagloy** [comment]
https://github.com/TechnionYP5779/team3/wiki/Push-Procedure!

**Comment by yossigil** [comment]
IT IS AN EMPTY PAGE

**Comment by IliaSmagloy** [comment]
There was a problem with the title, it has been fixed.
Thank you for the notice, closed for good.
