### ISSUE TITLE
Reopen all non-trivial issues, and make sure that someone else closes them

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team3#82]
_From @yossigil on November 14, 2018 9:2_

in particular, if you closed an non-trivial issue, reopen it, and ask someone else in your team verifies that the issue can be closed.

_Copied from original issue: TechnionYP5779/team6#76_

**Comment by yossigil** [comment]
Do not close this issue, without demonstrating that you indeed fixed some closed issues.

**Comment by yossigil** [comment]
Please add a commit number for all issues that were closed without a commit number.
This is an exercise in searching git history

**Comment by yossigil** [comment]
labels/assigneed/milestone?

**Comment by yanivbaldi** [comment]
All the reopened issues have been checked and closed again by another team member.
