### ISSUE TITLE
Test runs should be with assertions enabled

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team3#84]
_From @yossigil on November 14, 2018 9:21_

Play with eclipse, it is better to write
`assert x`
then
`azzert.isTrue(x)`

but when you run tests the jvm should have assertions enabled

_Copied from original issue: TechnionYP5779/team6#82_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#81

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#66

**Comment by yossigil** [comment]
You should use a jvm flag. Can you please show where this flag is set? use screen dump if necessary

**Comment by anny234** [comment]
![image](https://user-images.githubusercontent.com/33667684/48698489-e5ce1700-ebef-11e8-97ba-1285b3781cd9.png)
flag was already in use
