### ISSUE TITLE
Integrate github issues with eclipse

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team3#85]
_From @yossigil on November 14, 2018 9:24_

for this, you need a proper mylyn connector. Best done by one team member figruing this out, and then
letting him instruct other members.

in short, github issues should be shown in the eclipse task list view.

![image](https://user-images.githubusercontent.com/12775400/48472870-e174b900-e7ff-11e8-8357-cf6c77bd12c5.png)

this is what the end results looks like in my machine. I can even see this issue on my eclipse:

![image](https://user-images.githubusercontent.com/12775400/48473379-03bb0680-e801-11e8-99b9-64c5d470c03a.png)

_Copied from original issue: TechnionYP5779/team6#83_

**Comment by dormaayan** [comment]
_From @yossigil on November 14, 2018 9:26_

be sure to enter the github password to and save it in eclipse, otherwise, you will get errors in synching.

here is where you add the password

![image](https://user-images.githubusercontent.com/12775400/48473150-8c857280-e800-11e8-8b18-152753de853c.png)

**Comment by dormaayan** [comment]
_From @yossigil on November 14, 2018 9:30_

![image](https://user-images.githubusercontent.com/12775400/48473035-3dd7d880-e800-11e8-8753-e906d36a448d.png)

this is where you add repos.

**Comment by dormaayan** [comment]
_From @yossigil on November 14, 2018 9:37_

hint, do an internet search

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#127

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#82

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#67

**Comment by anny234** [comment]
![image](https://user-images.githubusercontent.com/33667684/48697893-68ee6d80-ebee-11e8-8027-77e0ab86b555.png)
#106 was created via eclipse as demostration :-)

**Comment by yossigil** [comment]
DOES THIS WORK FOR **ALL** TEAM MEMBERS

**Comment by eric-K1** [comment]
Here it is on my machine:
![image](https://user-images.githubusercontent.com/44426565/48794529-f3c08c80-ed02-11e8-95c4-d988190f855b.png)

**Comment by DanielaDii** [comment]
![default](https://user-images.githubusercontent.com/44427246/48796915-85cb9380-ed09-11e8-8f9f-f117ea600f61.png)

**Comment by eladyundler** [comment]
![image](https://user-images.githubusercontent.com/38835610/48797766-bf9d9980-ed0b-11e8-99c1-a9a139328b5c.png)

**Comment by IliaSmagloy** [comment]
![image](https://user-images.githubusercontent.com/23378405/48798503-73ebef80-ed0d-11e8-9897-4669304790d0.png)
