### ISSUE TITLE
  @SuppressWarnings("boxing")

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team3#90]
_From @yossigil on November 14, 2018 11:9_

This should never occur in the code, perhaps with the exception of class "box"
Use class box, and/or box.it() instead.

Only close this issue with a screen dump showing search for   @SuppressWarnings("boxing")

_Copied from original issue: TechnionYP5779/team6#87_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#129

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team4#114

**Comment by yossigil** [comment]
good job

**Comment by yossigil** [comment]
this is what I get when I search for "boxing"

![image](https://user-images.githubusercontent.com/12775400/48593462-9a004100-e955-11e8-8321-066ada088830.png)

**Comment by anny234** [comment]
There are only comments:
![image](https://user-images.githubusercontent.com/33667684/48619461-3f8ed100-e9a5-11e8-8d6c-daba0cc03f7b.png)
