### ISSUE TITLE
@SuppressWarning of "static-method"

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team3#91]
_From @yossigil on November 14, 2018 10:54_

If a unit test class does not use fixtures, all its methods would get "static-method" warning. Make sure that that in all unit tests like this, "static-method"  warning is suppressed in the class definition.

Do look up "fixtures" and read about junit 

_Copied from original issue: TechnionYP5779/team6#86_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#130

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team4#115

**Comment by DanielaDii** [comment]
https://junit.org/junit4/cookbook.html
http://sqa.fyicenter.com/FAQ/JUnit/What_Is_a_JUnit_Test_Fixture_.html
Info about fixtures(in case someone would like to read about the issue)
