### ISSUE TITLE
Create a cleanup profile for eclipse, and save it with your projecrt

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team3#92]
_From @yossigil on November 14, 2018 11:21_

Connect this profile with the wiki you created for a commit procedure

![image](https://user-images.githubusercontent.com/12775400/48479501-315b7c00-e810-11e8-997e-c2a63792c609.png)

_Copied from original issue: TechnionYP5779/team6#88_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#131

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team4#116

**Comment by yanivbaldi** [comment]
Checked.
