### ISSUE TITLE
Convert azzert.that(X, is(true)) to assert x

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team3#93]
_From @yossigil on November 14, 2018 20:39_

Similalry, convert azzert.that(X, is(false)) to assert !x
Similalry, convert azzert.thattrue, is(Boolean.FALSE)) to assert !x,
etc.

_Copied from original issue: TechnionYP5779/team6#90_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#133

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team4#119

**Comment by yanivbaldi** [comment]
I have checked, and these functions are not used.
