### ISSUE TITLE
move azzertTests to the test hierarchy

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team3#95]

**Comment by yanivbaldi** [comment]
![image](https://user-images.githubusercontent.com/37808851/48558383-d69a5100-e8f1-11e8-969c-98192940f1c9.png)

@yossigil It's ok?

**Comment by yanivbaldi** [comment]
![image](https://user-images.githubusercontent.com/37808851/48674335-976b3a80-eb53-11e8-8a24-796b2ad2946e.png)
azzertTests is in the test hierarchy
