### ISSUE TITLE
Yaniv Baldinger - personal work

### ISSUE THREAD

**Issue by yanivbaldi** [TechnionYP5779/team3#97]

**Comment by yossigil** [comment]
?

**Comment by yanivbaldi** [comment]
### **Sprint Zero** 
The TDD i worked on: angle #71 
The more time-consuming issues I worked on:

- #35 coverage 60% (my major work on Sprint 0 was on that issue)

- #89 eliminate all SuppressWarnings

- #71 angle TDD

- #16 Test for box

- #17 Test for idimatic

**All work in the sprint:**

- #4 good first issue

- #15 Unit tests for class Bool

- #16 Unit test for class box

- #17 Unit test for class idiomatic

- #35 increase code coverage to 60% (main issue)

- #71 use TDD to define class angle

- #73 clean run of tests 

- #82 reopen non-trivial issues

- #89 eliminate all SuppressWarnings (helped) 

- #93 convert azzert.that(X, is(true)) to assert x

- #94 move nilTest to the test hierarchy

- #95 move azzertTest to the test hierarchy

- #114 rename test classes to be XTest for class X

- #125 move de to fluent.ly

- #126 Upgrade to Java 11: https://goo.gl/xBf7iR 

- #128 clean test run



### **Sprint One** 

**Main work on Sprint One :**
- Web design - issues: #154, #153, #152 
- Add filters for search - issues: #224, #226, #227 
- Split parking hours range when rented (#235) - this feature almost got in (see in the presentation of sprint 1)

**More issues that I worked on:** 
- Plan DB schema - (#135)
- Update team members in README - (#144)
- Fix contributors file - (#142)
- Prepare questions for survey - (#98)

**note:** my free week was in the middle of sprint 1

**Comment by yossigil** [comment]
This does not appear to be much, and some of the work you claim, belongs to others.
Overall, not good.
