### ISSUE TITLE
prepare questions for survey until the next meeting

### ISSUE THREAD

**Issue by yanivbaldi** [TechnionYP5779/team3#98]

**Comment by yossigil** [comment]
MILESTONE

**Comment by anny234** [comment]
@yossigil is it still Sprint-Zero? because this is about our project idea and not the current code?

**Comment by yossigil** [comment]
you were supposed to create a milestone for project selection

**Comment by DanielaDii** [comment]
We splitted this issue to survey issue and mail issue, so we can close this one. (See virtual meating 1 wiki for details)
